### ISSUE TITLE
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded

### ISSUE THREAD

**Issue by julianloaizal** [amineboutarfi/booking_scraper#1]
Hello, I have downloaded the code and configured accordingly as it is in the readme, but when I run it, it does not generate the csv.

I get errors with playwright TimeoutError.

Can you help me correct this error?

There are: 25 hotels.
Traceback (most recent call last):
  File "/home/julian/Downloads/booking_scraper-master/booking_scraper1.py", line 45, in <module>
    main()
  File "/home/julian/Downloads/booking_scraper-master/booking_scraper1.py", line 30, in main
    hotel_dict['price'] = hotel.locator('//span[@data-testid="price-and-discounted-price"]').inner_text()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julian/Downloads/booking_scraper-master/venv/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 16853, in inner_text
    self._sync(self._impl_obj.inner_text(timeout=timeout))
  File "/home/julian/Downloads/booking_scraper-master/venv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/julian/Downloads/booking_scraper-master/venv/lib/python3.11/site-packages/playwright/_impl/_locator.py", line 406, in inner_text
    return await self._frame.inner_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julian/Downloads/booking_scraper-master/venv/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 610, in inner_text
    return await self._channel.send("innerText", locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julian/Downloads/booking_scraper-master/venv/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julian/Downloads/booking_scraper-master/venv/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/julian/Downloads/booking_scraper-master/venv/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("xpath=//div[@data-testid=\"property-card\"]").first.locator("xpath=//span[@data-testid=\"price-and-discounted-price\"]")
`============================================================```

**Comment by amineboutarfi** [comment]
Hello @julianloaizal. Are you sure this isn't a slow internet error? What did you search for so that I replicate it?

**Comment by julianloaizal** [comment]
I was already able to fix the problem by using ".all_inner_texts()" for the fields it retrieves with no data
![image](https://user-images.githubusercontent.com/37344931/235805348-1d2ef2fe-50a3-4f7f-8b8d-213e486fe4d4.png)
